/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sgubs.Apresentacao;

/**
 *
 * @author dayvison
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        CPaciente = new javax.swing.JMenuItem();
        CMedico = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        CConsultas = new javax.swing.JMenu();
        MenuPrincipal = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        btnFechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(java.awt.SystemColor.controlHighlight);

        jMenu3.setBackground(java.awt.Color.black);
        jMenu3.setForeground(java.awt.Color.black);
        jMenu3.setText("Cadastros");

        CPaciente.setText("Paciente");
        CPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPacienteActionPerformed(evt);
            }
        });
        jMenu3.add(CPaciente);

        CMedico.setText("Medico");
        CMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMedicoActionPerformed(evt);
            }
        });
        jMenu3.add(CMedico);
        jMenu3.add(jSeparator1);

        jMenuBar1.add(jMenu3);

        CConsultas.setForeground(java.awt.Color.black);
        CConsultas.setText("Consultas");
        jMenuBar1.add(CConsultas);

        MenuPrincipal.setForeground(java.awt.Color.black);
        MenuPrincipal.setText("Farmacia");
        MenuPrincipal.add(jSeparator2);

        jMenuBar1.add(MenuPrincipal);

        btnFechar.setForeground(java.awt.Color.black);
        btnFechar.setText("Fechar");
        btnFechar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                btnFecharMenuCanceled(evt);
            }
        });
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        jMenuBar1.add(btnFechar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
          this.dispose(); 
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnFecharMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_btnFecharMenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharMenuCanceled

    private void CPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPacienteActionPerformed
        TelaCadastroPaciente entrar = new TelaCadastroPaciente();
          entrar.setVisible(true);
          dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CPacienteActionPerformed

    private void CMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMedicoActionPerformed
        /*Teste teste=new Teste();
        Teste.criar();
        Teste.abrir();*/
        TelaCadastroMedico entrar=new TelaCadastroMedico();
        entrar.setVisible(true);
        dispose();

    }//GEN-LAST:event_CMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CConsultas;
    private javax.swing.JMenuItem CMedico;
    private javax.swing.JMenuItem CPaciente;
    private javax.swing.JMenu MenuPrincipal;
    private javax.swing.JMenu btnFechar;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
