/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sgubs.Apresentacao_Desktop;

/**
 *
 * @author dayvison
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal1
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        PainelFundo = new javax.swing.JLabel();
        jButtonMedicos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonMedicos1 = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jButtonMedicos3 = new javax.swing.JButton();
        principal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        MenuEspecialidade = new javax.swing.JMenuItem();
        MenuFuncionarios = new javax.swing.JMenuItem();
        MenuMedicamento = new javax.swing.JMenuItem();
        MenuMedicos = new javax.swing.JMenuItem();
        MenuPacientes = new javax.swing.JMenuItem();
        MenuTecEnfermagem = new javax.swing.JMenuItem();
        MenuUnidadeDeSaude = new javax.swing.JMenuItem();
        MenuConsultas = new javax.swing.JMenu();
        MenuFarmacia = new javax.swing.JMenu();
        MenuSairLogoff = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuLogoff = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGUBS-Sistema De Gerenciamento De Unidade Basíca De Saúde");
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setTitle("Acesso Rápido");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLayeredPane1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jLayeredPane1CaretPositionChanged(evt);
            }
        });

        PainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconengrenagem.png"))); // NOI18N
        jLayeredPane1.add(PainelFundo);
        PainelFundo.setBounds(580, -60, 770, 360);

        jButtonMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconTecEnfermagem.png"))); // NOI18N
        jButtonMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicosActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonMedicos);
        jButtonMedicos.setBounds(370, 40, 110, 110);

        jLabel2.setText("Cadastros :");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(10, 10, 77, 17);

        jButtonMedicos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconMedico.jpg"))); // NOI18N
        jButtonMedicos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicos1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonMedicos1);
        jButtonMedicos1.setBounds(10, 40, 110, 110);

        jButtonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconPaciente.png"))); // NOI18N
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonPaciente);
        jButtonPaciente.setBounds(130, 40, 110, 110);

        jButtonMedicos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconMedicamento.png"))); // NOI18N
        jButtonMedicos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicos3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonMedicos3);
        jButtonMedicos3.setBounds(250, 40, 110, 110);

        jInternalFrame1.getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 80, 870, 624);
        jInternalFrame1.getContentPane().add(principal);
        principal.setBounds(-10, 0, 880, 600);

        jLabel1.setText("Sistema de Gerenciamento de Unidades Basica de Saúde");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 7, 400, 30);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 60, 880, 490);

        MenuPrincipal.setName(""); // NOI18N

        MenuCadastros.setText("Cadastros");

        MenuEspecialidade.setText("Especialidades");
        MenuEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEspecialidadeActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuEspecialidade);

        MenuFuncionarios.setText("Funcionários");
        MenuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFuncionariosActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuFuncionarios);

        MenuMedicamento.setText("Medicamentos");
        MenuMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMedicamentoActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuMedicamento);

        MenuMedicos.setText("Medicos");
        MenuMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMedicosActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuMedicos);

        MenuPacientes.setText("Pacientes");
        MenuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPacientesActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuPacientes);

        MenuTecEnfermagem.setText("Téc Enfermagem");
        MenuTecEnfermagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTecEnfermagemActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuTecEnfermagem);

        MenuUnidadeDeSaude.setText("Unidades De Saúde");
        MenuUnidadeDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUnidadeDeSaudeActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuUnidadeDeSaude);

        MenuPrincipal.add(MenuCadastros);

        MenuConsultas.setText("Consultas");
        MenuPrincipal.add(MenuConsultas);

        MenuFarmacia.setText("Farmacia");
        MenuPrincipal.add(MenuFarmacia);

        MenuSairLogoff.setText("Sair/Logoff");
        MenuSairLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairLogoffActionPerformed(evt);
            }
        });

        jMenuItem1.setText("ControleUsuario");
        MenuSairLogoff.add(jMenuItem1);

        MenuLogoff.setText("Logoff");
        MenuLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogoffActionPerformed(evt);
            }
        });
        MenuSairLogoff.add(MenuLogoff);

        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        MenuSairLogoff.add(MenuSair);

        MenuPrincipal.add(MenuSairLogoff);

        setJMenuBar(MenuPrincipal);

        setSize(new java.awt.Dimension(887, 574));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPacientesActionPerformed
        TelaPacienteListagem tela=new TelaPacienteListagem();
        this.add(tela);
        tela.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_MenuPacientesActionPerformed

    private void MenuMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMedicosActionPerformed
        TelaMedicoListagem tela=new TelaMedicoListagem();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuMedicosActionPerformed

    private void MenuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFuncionariosActionPerformed

    private void MenuLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogoffActionPerformed
        new TelaLogin().setVisible(true);

    }//GEN-LAST:event_MenuLogoffActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_MenuSairActionPerformed

    private void MenuSairLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairLogoffActionPerformed
        //System.exit(0);
               // TODO add your handling code here:
    }//GEN-LAST:event_MenuSairLogoffActionPerformed

    private void MenuEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEspecialidadeActionPerformed
       TelaEspecialidadeListagem tela = new TelaEspecialidadeListagem();
       this.add(tela);
       tela.setVisible(true);
    }//GEN-LAST:event_MenuEspecialidadeActionPerformed

    private void MenuUnidadeDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUnidadeDeSaudeActionPerformed
       TelaUnidadeDeSaudeListagem tela = new TelaUnidadeDeSaudeListagem();
       this.add(tela);
       tela.setVisible(true);
        
    }//GEN-LAST:event_MenuUnidadeDeSaudeActionPerformed

    private void MenuTecEnfermagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTecEnfermagemActionPerformed
       TelaTecEnfermagemListagem tela = new TelaTecEnfermagemListagem();
       this.add(tela);
       tela.setVisible(true);
       
    }//GEN-LAST:event_MenuTecEnfermagemActionPerformed

    private void MenuMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMedicamentoActionPerformed
        TelaMedicamentoListagem tela = new TelaMedicamentoListagem();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuMedicamentoActionPerformed

    private void jLayeredPane1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLayeredPane1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLayeredPane1CaretPositionChanged

    private void jButtonMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicosActionPerformed
        TelaMedicoListagem tela=new TelaMedicoListagem();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonMedicosActionPerformed

    private void jButtonMedicos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedicos1ActionPerformed

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    private void jButtonMedicos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedicos3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenu MenuConsultas;
    private javax.swing.JMenuItem MenuEspecialidade;
    private javax.swing.JMenu MenuFarmacia;
    private javax.swing.JMenuItem MenuFuncionarios;
    private javax.swing.JMenuItem MenuLogoff;
    private javax.swing.JMenuItem MenuMedicamento;
    private javax.swing.JMenuItem MenuMedicos;
    private javax.swing.JMenuItem MenuPacientes;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem MenuSair;
    private javax.swing.JMenu MenuSairLogoff;
    private javax.swing.JMenuItem MenuTecEnfermagem;
    private javax.swing.JMenuItem MenuUnidadeDeSaude;
    private javax.swing.JLabel PainelFundo;
    private javax.swing.JButton jButtonMedicos;
    private javax.swing.JButton jButtonMedicos1;
    private javax.swing.JButton jButtonMedicos3;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel principal;
    // End of variables declaration//GEN-END:variables
}
