/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sgubs.Apresentacao_Desktop;

import br.edu.ifnmg.sgubs.Aplicacao.Agendamento;
import br.edu.ifnmg.sgubs.Aplicacao.AgendamentoRepositorio;
import java.sql.Time;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dayvison
 */
public class TelaAgendamentoListagem extends javax.swing.JInternalFrame {
    
    AgendamentoRepositorio dao = GerenciadorReferencias.getAgendamento();
    
    TelaAgendamentoEditar editar;

    /**
     * Creates new form TelaAgendamento
     */
    public TelaAgendamentoListagem() {
        initComponents();
        
        preencheTabela(dao.Buscar(null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();

        btnNovo.setText("Novo Agendamento");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListagemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListagemMouseClicked
        int selecionada = tblListagem.getSelectedRow();

        int id = Integer.parseInt( tblListagem.getModel().getValueAt(selecionada, 0).toString() );

        editarAgendamento(id);
    }//GEN-LAST:event_tblListagemMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        editarAgendamento(0);
    }//GEN-LAST:event_btnNovoActionPerformed

     private void preencheTabela(List<Agendamento> lista){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Unidade");
        modelo.addColumn("Medico");
        modelo.addColumn("Paciente");
        modelo.addColumn("Hora");
        modelo.addColumn("Data");
        
        for(Agendamento a : lista){
            Vector linha = new Vector();
            linha.add(a.getId());
            linha.add(a.getUnidadeSaude());
            linha.add(a.getMedico());
            linha.add(a.getPaciente());
            linha.add(a.getHorario().toString());
            linha.add(a.getData().toString());
            
            modelo.addRow(linha);
        }
        
        tblListagem.setModel(modelo);
    }
//gendamento(int id, int idUnidadeSaude, int idMedico, int idPaciente, Time horario, Date data
     public void editarAgendamento(int id){
        Agendamento entidade;
        if(id == 0)
            entidade = new Agendamento(id,null,null,null,null,new Date());
        else
            entidade = dao.Abrir(id);
        
        editar = new TelaAgendamentoEditar();
        
        editar.setEntidade(entidade);
        
        editar.setListagem(this);
        
        this.getParent().add(editar);
        editar.setVisible(true);
        this.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListagem;
    // End of variables declaration//GEN-END:variables
}
