/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sgubs.Apresentacao_Desktop;

import br.edu.ifnmg.sgubs.Aplicacao.ErroValidacao;
import br.edu.ifnmg.sgubs.Aplicacao.Paciente;
import br.edu.ifnmg.sgubs.Aplicacao.PacienteRepositorio;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dayvison
 */
public class TelaPacienteEditar extends javax.swing.JInternalFrame {
    
    Paciente entidade;
    
    PacienteRepositorio dao;
    
    TelaPacienteListagem listagem;
    
    Paciente paciente = new Paciente();

    /**
     * Creates new form TelaPacienteEditar
     */
    public TelaPacienteEditar() {
        initComponents();
        
        dao = GerenciadorReferencias.getPaciente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextoBairro = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        TextoCidade = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        TextoCel = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        TextoTelefone = new javax.swing.JLabel();
        TextoTipoSanguineo = new javax.swing.JLabel();
        TextoLocalTrabalho = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        TextoCod = new javax.swing.JLabel();
        TextoNome = new javax.swing.JLabel();
        TextoCrm = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        TextoRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        txtLocalTrabalho = new javax.swing.JTextField();
        bntListar = new javax.swing.JButton();
        cbxTipoSanguineo = new javax.swing.JComboBox<>();
        bntExcluir = new javax.swing.JButton();
        bntNovo = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Paciêntes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TextoBairro.setText("Bairro:");

        TextoCidade.setText("Cidade:");

        TextoCel.setText("Cel:");

        TextoTelefone.setText("Telefone:");

        TextoTipoSanguineo.setText("Tipo Sanguineo :");

        TextoLocalTrabalho.setText("Local de Trabalho :");

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        TextoCod.setText("CodPaciente:");

        TextoNome.setText("Nome:");

        TextoCrm.setText("Cpf :");

        TextoRua.setText("Rua:");

        bntSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        bntListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listar.png"))); // NOI18N
        bntListar.setText("Listar");
        bntListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntListarActionPerformed(evt);
            }
        });

        cbxTipoSanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O-", "A-", "B-", "AB-", "O+" }));

        bntExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        bntNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        bntNovo.setText("Novo");
        bntNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxTipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoBairro)
                                    .addComponent(TextoCel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCelular)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoCidade)
                            .addComponent(TextoTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone)
                            .addComponent(txtCidade)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoTipoSanguineo)
                                    .addComponent(TextoLocalTrabalho))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLocalTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoNome)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TextoRua)
                                        .addComponent(TextoCrm)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCpf)
                                        .addGap(236, 236, 236))
                                    .addComponent(txtRua)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextoCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bntNovo)
                                        .addGap(18, 18, 18)
                                        .addComponent(bntSalvar)
                                        .addGap(30, 30, 30)
                                        .addComponent(bntListar)
                                        .addGap(18, 18, 18)
                                        .addComponent(bntExcluir))
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSalvar)
                    .addComponent(bntListar)
                    .addComponent(bntExcluir)
                    .addComponent(bntNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoCod)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCrm)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoRua)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextoCidade)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextoBairro)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCel)
                    .addComponent(TextoTelefone)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoTipoSanguineo)
                    .addComponent(cbxTipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoLocalTrabalho)
                    .addComponent(txtLocalTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Validacao() throws ParseException, ErroValidacao {
    

        String nome = txtNome.getText().trim();
        if(!nome.equals("")){
            paciente.setNome(nome);
        }else {
            JOptionPane.showMessageDialog(this, "Digite o Nome do Paciente");
        }
        
        String cpf = txtCpf.getText().trim();
        if(!cpf.equals("")){
            paciente.setCpf(cpf);
        }else {
            JOptionPane.showMessageDialog(this, "Digite o Cpf do Paciente");
        }
        
        String rua = txtRua.getText().trim();
        if(!rua.equals("")){
            paciente.setRua(rua);
        }else {
            JOptionPane.showMessageDialog(this, "Digite a Rua do Paciente");
        }
        
        String bairro = txtBairro.getText().trim();
        if(!bairro.equals("")){
            paciente.setBairro(bairro);
        }else {
            JOptionPane.showMessageDialog(this, "Digite o Bairro do Paciente");
        }
        
        String cidade = txtCidade.getText().trim();
        if(!cidade.equals("")){
            paciente.setCidade(cidade);
        }else {
            JOptionPane.showMessageDialog(this, "Digite a cidade do Paciente");
        }
        
       // String tipo = txtTipoSanguineo.getText().trim();
       // if(!tipo.equals("")){
           // paciente.setTipoSanguineo(tipo);
           // JOptionPane.showMessageDialog(this, "Digite o tipo sanguineo do Paciente");
       // }
        
        String trabalho = txtLocalTrabalho.getText().trim();
        if(!trabalho.equals("")){
            paciente.setLocalTrabalho(trabalho);
        }else {
            JOptionPane.showMessageDialog(this, "Digite o Local de Trabalho do Paciente");
        }
        
    }
    
    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed

        try {
            
            this.Validacao();

            if(JOptionPane.showConfirmDialog(rootPane, "Deseja salvar alterações ?") == 0){
                
                preencheObjeto();
              
                if(dao.Salvar(entidade))
                
                    JOptionPane.showMessageDialog(rootPane, "Dados salvos com sucesso !");

                else
                
                    JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro durante o processo !");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada !");
            }

        } catch (ErroValidacao ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());

        } catch (ParseException ex) {
            Logger.getLogger(TelaPacienteEditar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListarActionPerformed
        listagem.setVisible( true);
        this.setVisible(false);
    }//GEN-LAST:event_bntListarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Deseja Excluir Esse Paciente ?") == 0){

            if(dao.Apagar(entidade)){
                JOptionPane.showMessageDialog(rootPane, "Dados Excluidos com sucesso !");
                entidade = new Paciente(0, "", "", "", "", "", 0, 0, "", "");
                preencheCampos();
            }
            else
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro durante o processo !");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Operação cancelada !");
        }

    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNovoActionPerformed
        entidade =new Paciente(0, "", "", "", "", "", 0, 0, "", "");
        preencheCampos();
    }//GEN-LAST:event_bntNovoActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    public Paciente getEntidade() {
        return entidade;
    }

    public void setEntidade(Paciente entidade) {
        this.entidade = entidade;
        preencheCampos();
    }
   
      private void preencheCampos(){
        lblCodigo.setText( Integer.toString( entidade.getId()));
        txtNome.setText( entidade.getNome());
        txtCpf.setText( entidade.getCpf());
        txtRua.setText( entidade.getRua());
        txtBairro.setText( entidade.getBairro());
        txtCidade.setText( entidade.getCidade());
        txtCelular.setText( Integer.toString(entidade.getCelular()));
        txtTelefone.setText( Integer.toString(entidade.getTelefone()));
        cbxTipoSanguineo.setSelectedItem(entidade.getTipoSanguineo());
        txtLocalTrabalho.setText( entidade.getLocalTrabalho());
                
        
    }
      
    private void preencheObjeto() throws ErroValidacao{
        entidade.setNome(txtNome.getText());
        entidade.setCpf( txtCpf.getText());
        entidade.setRua( txtRua.getText());
        entidade.setBairro( txtBairro.getText());
        entidade.setCidade( txtCidade.getText());
        entidade.setCelular(Integer.parseInt(txtCelular.getText()));
        entidade.setTelefone( Integer.parseInt(txtTelefone.getText()));
        entidade.setTipoSanguineo( (String) cbxTipoSanguineo.getSelectedItem());
        entidade.setLocalTrabalho(txtLocalTrabalho.getText());
                
    }
    
    public TelaPacienteListagem getListagem(){
        return listagem;
    }
    
    public void setListagem(TelaPacienteListagem listagem){
        this.listagem = listagem;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoBairro;
    private javax.swing.JLabel TextoCel;
    private javax.swing.JLabel TextoCidade;
    private javax.swing.JLabel TextoCod;
    private javax.swing.JLabel TextoCrm;
    private javax.swing.JLabel TextoLocalTrabalho;
    private javax.swing.JLabel TextoNome;
    private javax.swing.JLabel TextoRua;
    private javax.swing.JLabel TextoTelefone;
    private javax.swing.JLabel TextoTipoSanguineo;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntListar;
    private javax.swing.JButton bntNovo;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JComboBox<String> cbxTipoSanguineo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtLocalTrabalho;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
